language: python
python:
  - "3.4"
  - "3.5"

# installs dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
# runs tests
script:
 nosetests --with-coverage
after_success:  
- coveralls