language: python
python:
  - "3.5"
  - "3.6"

install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:

  coverage run tests/test_cases.py -m unittest

after_success:
  coveralls