language: python
python:
  - "3.5"
  - "3.6"

install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install SQLAlchemy"

script:

  coverage run --source=modules/ tests/test_cases.py

after_success:
  coveralls
